#!/usr/bin/env python2

# Copyright (C) 2014 Science and Technology Facilities Council.
# Copyright (C) 2015 East Asian Observatory.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse

from insertnamehere.web.app import create_web_app

parser = argparse.ArgumentParser()
parser.add_argument('--debug', required=False, default=False,
                    action='store_true')

args = parser.parse_args()

app = create_web_app()

options = {
    'port': 5678,
}

if args.debug:
    options['host'] = '127.0.0.1'
    options['debug'] = True

else:
    options['host'] = '0.0.0.0'
    options['debug'] = False

app.run(**options)
